### ISSUE TITLE
Вроде говорили, что нужно ещё хранить цену, за которую продали

### ISSUE THREAD

**Issue by coursar** [arakhmatullin/HW.ulmartdb#4]
https://github.com/arakhmatullin/HW.ulmartdb/blob/f1f8dfefdc37b59c604bbd81ebeebee4859bdae5/src/main/resources/requests.sql#L53-L59

**Comment by arakhmatullin** [comment]
Мне показалось что уместнее ее будет хранить в таблице store (функционал склада). При изменении продажной цены в таблице склад создается новая запись с новой ценой и в нее переносятся остатки из текущей записи.
